# APE Framework Configuration File

contracts_folder: contracts

solidity:
  version: 0.8.24

plugins:
  - name: hardhat==0.6.13
  - name: solidity==0.6.11

# Ignore `bindings.sol` to speed up compilation. This is because compiling it
# doesn't result in a cached JSON file under `.build/`, and so it must be
# re-compiled every time APE runs.
compiler:
  ignore_files:
    - "*package.json"
    - "*package-lock.json"
    - "*tsconfig.json"
    - "bindings.sol"
