version: '3.3'
services:
  node1:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: autonity
    volumes:
      - ./nodekey1:/nodekey:ro
      - ./keystore:/keystore:ro
      - ./genesis-tendermint.json:/genesis.json:ro
      - ./autonity-start.sh:/autonity-start.sh:ro
    ports:
      - 8541:8545
      - 8641:8645
      - 30313:30303
      - "30313:30303/udp"
    entrypoint: ''
    command: ["./autonity-start.sh"]
    container_name: autonity-node-1
    networks:
      chainnet:
        ipv4_address: 172.25.0.11
  node2:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: autonity
    volumes:
      - ./nodekey2:/nodekey:ro
      - ./keystore:/keystore:ro
      - ./genesis-tendermint.json:/genesis.json:ro
      - ./autonity-start.sh:/autonity-start.sh:ro
    ports:
      - 8542:8545
      - 8642:8645
      - 30323:30303
      - "30323:30303/udp"
    entrypoint: ''
    command: ["./autonity-start.sh"]
    container_name: autonity-node-2
    networks:
      chainnet:
        ipv4_address: 172.25.0.12
  node3:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: autonity
    volumes:
      - ./nodekey3:/nodekey:ro
      - ./keystore:/keystore:ro
      - ./genesis-tendermint.json:/genesis.json:ro
      - ./autonity-start.sh:/autonity-start.sh:ro
    ports:
      - 8543:8545
      - 8643:8645
      - 30333:30303
      - "30333:30303/udp"
    entrypoint: ''
    command: ["./autonity-start.sh"]
    container_name: autonity-node-3
    networks:
      chainnet:
        ipv4_address: 172.25.0.13
  node4:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: autonity
    volumes:
      - ./nodekey4:/nodekey:ro
      - ./keystore:/keystore:ro
      - ./genesis-tendermint.json:/genesis.json:ro
      - ./autonity-start.sh:/autonity-start.sh:ro
    ports:
      - 8544:8545
      - 8644:8645
      - 30343:30303
      - "30343:30303/udp"
    entrypoint: ''
    command: ["./autonity-start.sh"]
    container_name: autonity-node-4
    networks:
      chainnet:
        ipv4_address: 172.25.0.14
  node5:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: autonity
    volumes:
      - ./nodekey5:/nodekey:ro
      - ./keystore:/keystore:ro
      - ./genesis-tendermint.json:/genesis.json:ro
      - ./autonity-start.sh:/autonity-start.sh:ro
    ports:
      - 8545:8545
      - 8645:8645
      - 30353:30303
      - "30353:30303/udp"
    entrypoint: ''
    command: ["./autonity-start.sh"]
    container_name: autonity-node-5
    networks:
      chainnet:
        ipv4_address: 172.25.0.15

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
