{{- $imageE2ETestEngine := .Values.imageAutonityE2ETestEngine -}}
{{- $namespace := .Release.Namespace -}}
{{- $validatorAddress := .Values.validators.ips -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-test-engine
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app: e2e-test-engine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: e2e-test-engine
    spec:
      containers:
        - name: e2e-test-engine
          image: {{ $imageE2ETestEngine.repository }}:{{ $imageE2ETestEngine.tag }}
          env:
          {{- if $validatorAddress }}
          - name: VALIDATOR_IPS
            value: "{{ range $i, $e := until (atoi (toString .Values.validators.num)) }}{{index $validatorAddress $i }} {{ end }}"
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          lifecycle:
            postStart:
              exec:
                command: ["python3", "e2etestengine.py", "./bin/autonity", "-b", "true"]
